version: "3"

services:
  db:
    image: mysql:latest
    # restart: always
    container_name: mysql-server
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db:/opt/homebrew/bin/mysqld